type Student implements BaseUser {
  name: String!
  email: String!
  mobileNo: String!
  username: String!
  enrollNo: String!
  class_: Class
  todos: [Todo!]
  roles: [Roles!]
}

input newStudent{
    enrollNo: String!
}

input modifiedStudent{
    name: String
    email: String
    mobileNo: String
    class_id: ID
}

